name: C++ CI (Unit Tests)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++-13

      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_CXX_COMPILER=g++-13 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Run Tests
        run: |
          ctest --test-dir build --output-on-failure
